### ISSUE TITLE
Cannot install manifest-tool 1.4.8

### ISSUE THREAD

**Issue by daltonv** [PelionIoT/manifest-tool#34]
When attempting to install I get this error:
```bash
pip install manifest-tool==1.4.8
Collecting manifest-tool==1.4.8
  Using cached manifest-tool-1.4.8.tar.gz (64 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/daltonv/repositories/OC_CCE7102_CCE7103_ASIC_programmer/asic-programmer-mbed/mbed-os/.venv/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-8_ydflp4/manifest-tool_79342852e4b34bef8794e849de49c790/setup.py'"'"'; __file__='"'"'/tmp/pip-install-8_ydflp4/manifest-tool_79342852e4b34bef8794e849de49c790/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-e12k0ych
         cwd: /tmp/pip-install-8_ydflp4/manifest-tool_79342852e4b34bef8794e849de49c790/
    Complete output (12 lines):
    Traceback (most recent call last):
      File "/tmp/pip-install-8_ydflp4/manifest-tool_79342852e4b34bef8794e849de49c790/setup.py", line 28, in <module>
        from pip._internal.download import PipSession
    ModuleNotFoundError: No module named 'pip._internal.download'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-8_ydflp4/manifest-tool_79342852e4b34bef8794e849de49c790/setup.py", line 30, in <module>
        from pip.req import parse_requirements
    ModuleNotFoundError: No module named 'pip.req'
    ----------------------------------------
```

I have tried this on Windows, Linux, and python 3.10.2, 3.7.6, and 2.7.14. All run into the same problem. Is this version no longer supported?

**Comment by JanneKiiskila** [comment]
Hei @daltonv  - please try version 1.5.2 instead, https://github.com/PelionIoT/manifest-tool/releases/tag/v1.5.2
